### ISSUE TITLE
3.4版本已经安装了 imagecorruptions还是报错

### ISSUE THREAD

**Issue by SmithKevin0** [Fafa-DL/Image-Augmentation#36]
Traceback (most recent call last):
  File "imgaug\augmenters\imgcorruptlike.py", line 151, in _call_imgcorrupt_func
ModuleNotFoundError: No module named 'imagecorruptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ImgAug3.4.py", line 129, in run
  File "imgaug\augmenters\meta.py", line 2008, in __call__
  File "imgaug\augmenters\meta.py", line 1979, in augment
  File "imgaug\augmenters\meta.py", line 641, in augment_batch_
  File "imgaug\augmenters\imgcorruptlike.py", line 1027, in _augment_batch_
  File "imgaug\augmenters\imgcorruptlike.py", line 297, in apply_gaussian_noise
  File "imgaug\augmenters\imgcorruptlike.py", line 153, in _call_imgcorrupt_func
ImportError: Could not import package `imagecorruptions`. This is an optional dependency of imgaug and must be installed manually in order to use augmenters from `imgaug.augmenters.imgcorrupt`. Use e.g. `pip install imagecorruptions` to install it. See also https://github.com/bethgelab/imagecorruptions for the repository of the package.

**Comment by Fafa-DL** [comment]
把增强的方法发在这，我看能否复现

**Comment by SmithKevin0** [comment]
iaa.imgcorruptlike.GaussianNoise(severity=2)

**Comment by Fafa-DL** [comment]
已修复，请下载最新[V3.4](https://github.com/Fafa-DL/Image-Augmentation/releases/download/V3.4/ImgAug3.4.exe)版本
